name: Build Cryptlex.LexFloatClient package

on:
  workflow_dispatch:
    inputs:
      libraryVersion:
        description: 'Library Version'
        required: true
        default: ''
      packageVersion:
        description: 'Package Version'
        required: true
        default: ''

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Update Package Version
        run: |
          sed -i '/<version>/!b;c \ \ \ \ <version>${{ github.event.inputs.packageVersion }}</version>' ./src/Cryptlex.LexFloatClient/Cryptlex.LexFloatClient.nuspec    
      
      - name: Update Library Version
        run: |
          sed -i '/lexfloatclient_version =/!b;c$lexfloatclient_version ="v${{ github.event.inputs.libraryVersion }}"' post-build.ps1
     
      - name: Commit, Tag and Push
        run: |
          git add ./src/Cryptlex.LexFloatClient/Cryptlex.LexFloatClient.nuspec
          git add post-build.ps1
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "updated version" | exit 0
          git tag ${{ github.event.inputs.packageVersion }}
          git push & git push --tags
     
  build-publish:
    needs: update-version
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - run: git pull origin master --ff-only

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.8.1'
      
    - name: Restore NuGet Packages
      run: nuget restore Cryptlex.LexFloatClient.sln
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Build Solution
      run: msbuild Cryptlex.LexFloatClient.sln /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0"
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with: 
        credentials_json: ${{ secrets.GCP_KMS_SIGNER_KEY }}

    - name: Run code signing script
      shell: powershell
      run: |
          .\code-sign.ps1 -SignType "dll"

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        install_components: 'gcloud'

    - name: Download Native Libs
      shell: powershell
      run: .\post-build.ps1
      
    - name: Pack NuGet Package
      run: nuget pack src\Cryptlex.LexFloatClient\Cryptlex.LexFloatClient.nuspec -NonInteractive -OutputDirectory nupkg -Properties Configuration=Release -Verbosity Detailed
    
    - name: Run NuGet package code signing script
      shell: powershell
      run: |
          .\code-sign.ps1 -SignType "nupkg"

    - name: Push NuGet Package
      run: nuget push nupkg\*.nupkg -SkipDuplicate -Source https://api.nuget.org/v3/index.json -NoSymbols

